# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Consentua
tagline:          'Blog'
description:      'Choice and Control for your personal data'
url:              http://blog.consentua.com
baseurl:          
home:             http://consentua.com
dashboard:        https://app.consentua.com
api:              http://api.consentua.com/swagger

author:
  name:           'Knownow Information'
  url:            https://kn-i.com

paginate:         2

gist:
  noscript: false

# Custom vars
version:          2.1.0

github:           
  repo:           davidpatto/consentuaBlog
repository:       davidpatto/consentuaBlog