# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            consentua
tagline:          'A Jekyll theme'
description:      'Consentua is a consent management tool that helps organisations to achieve data protection compliance, and gives individuals choice and control over how their personal data is used.'
url:              http://blog.consentua.com
baseurl:          '/'

author:
  name:           'Knownow Information'
  url:            https://kn-i.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mrsideshowjack/consentuaBlog
