# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            consentua
tagline:          'Blog'
description:      'Choice and Control for your personal Data'
url:              http://blog.consentua.com
baseurl:          '/consentuaBlog'
home:             http://consentua.com
dashboard:        https://app.consentua.com
api:              http://api.consentua.com/swagger

author:
  name:           'Knownow Information'
  url:            https://kn-i.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mrsideshowjack/consentuaBlog
