# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            consentua
tagline:          'A Jekyll theme'
description:      'Choice and Control for your personal Data'
url:              http://blog.consentua.com
baseurl:          '/consentuaBlog/'

author:
  name:           'Knownow Information'
  url:            https://kn-i.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mrsideshowjack/consentuaBlog
